name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch: {}
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Generate snake game SVG
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-contribution-grid-snake-violet.svg?palette=violet
            dist/github-contribution-grid-snake-yellow.svg?palette=yellow
            dist/github-contribution-snake.svg

      - name: Create output directory
        run: mkdir -p output

      - name: Copy files to output directory
        run: cp dist/* output/

      - name: Commit & Push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add -A .
          git commit -m "generated contribution snake" || exit 0
          git push